// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Pomodoro
{
    internal sealed partial class Vsix
    {
        public const string Id = "f8900f8f-2d5b-4c3f-91b3-146283e99eed";
        public const string Name = "Pomodoro Timer";
        public const string Description = @"This extension keeps track of your time using the famous Pomodoro method";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
