// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Pomodoro
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPomodoroPackageString = "80809696-9425-4d69-854e-0d0f74869732";
        public static Guid guidPomodoroPackage = new Guid(guidPomodoroPackageString);

        public const string guidPomodoroPackageCmdSetString = "f63ab421-840b-48b8-859b-550f8ce3107d";
        public static Guid guidPomodoroPackageCmdSet = new Guid(guidPomodoroPackageCmdSetString);

        public const string MyImagesString = "d63849c7-5069-4409-8148-acfdc8ec5c17";
        public static Guid MyImages = new Guid(MyImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TimerToolWindowCommandId = 0x0100;
        public const int logo = 0x0001;
    }
}